trigger: ["master"]
pr: ["master"]

variables:
  features: ''
  bench: 'false'

strategy:
  matrix:
    windows-nightly:
      imageName: 'vs2017-win2016'
      rust: nightly
    mac-nightly:
      imageName: 'macos-10.13'
      rust: nightly
      bench: 'true'
    # linux-stable:
    #   imageName: 'ubuntu-16.04'
    #   rust: stable
    #   features: '--no-default-features --features runtime,__internal_happy_eyeballs_tests'
    # linux-stable-no-features:
    #   imageName: 'ubuntu-16.04'
    #   rust: stable
    #   features: '--no-default-features'
    # linux-beta:
    #   imageName: 'ubuntu-16.04'
    #   rust: beta
    #   features: '--no-default-features --features runtime,__internal_happy_eyeballs_tests'
    linux-nightly:
      imageName: 'ubuntu-16.04'
      rust: nightly
      features: '--no-default-features --features runtime,nightly'
      bench: 'true'
    # linux-minimum-supported-version:
    #   imageName: 'ubuntu-16.04'
    #   rust: stable
    #   features: '--no-default-features --features runtime'

pool:
  vmImage: $(imageName)

steps:
  - template: ci/azure-install-rust.yml
    parameters:
      rust_version: $(rust)
  - template: ci/azure-test.yml
    parameters:
      features: $(features)
      bench: $(bench)
