[package]

name = "hyper"
version = "0.3.4"
description = "A modern HTTP library."
readme = "README.md"
documentation = "http://hyperium.github.io/hyper/hyper/index.html"
repository = "https://github.com/hyperium/hyper"
license = "MIT"
authors = ["Sean McArthur <sean.monstar@gmail.com>",
           "Jonathan Reem <jonathan.reem@gmail.com>"]
keywords = ["http", "hyper", "hyperium"]

[dependencies]
httparse = "*"
log = ">= 0.2.0"
time = "*"
num_cpus = "*"
url = "*"

[dependencies.hypernet]
path = "hypernet"

[dependencies.hyperprotocol]
path = "hyperprotocol"

[dev-dependencies]
env_logger = "*"

[dev-dependencies.hypernet]
path = "hypernet"
features = ["mock"]
