[package]

name = "hyper"
version = "1.0.0"
description = "A modern HTTP library."
readme = "README.md"
documentation = "http://hyperium.github.io/hyper/hyper/index.html"
repository = "https://github.com/hyperium/hyper"
license = "MIT"
authors = ["Sean McArthur <sean.monstar@gmail.com>",
           "Jonathan Reem <jonathan.reem@gmail.com>"]

[dependencies.hyper-core]
path = "src/core/"
version = "0.1.0"
[dependencies.hyper-protocol]
path = "src/protocol/"
version = "0.1.0"
[dependencies.hyper-net]
path = "src/net/"
optional = true
version = "0.1.0"
[dependencies.hyper-client]
path = "src/client/"
optional = true
version = "0.1.0"
[dependencies.hyper-server]
path = "src/server/"
optional = true
version = "0.1.0"
[features]
default = [ "hyper-client", "hyper-server" , "hyper-net" ]
net = [ "hyper-net" ]
server = [ "hyper-server", "hyper-net" ]
client = [ "hyper-client", "hyper-net" ]
[dependencies.url]
version = "*"
[dependencies.mime]
version = "*"

[dev-dependencies.curl]
version = "*"

[dev-dependencies.http]
version = "*"
