[package]

name = "hyper"
version = "0.5.0"
description = "A modern HTTP library."
readme = "README.md"
documentation = "http://hyperium.github.io/hyper/hyper/index.html"
repository = "https://github.com/hyperium/hyper"
license = "MIT"
authors = ["Sean McArthur <sean.monstar@gmail.com>",
           "Jonathan Reem <jonathan.reem@gmail.com>"]
keywords = ["http", "hyper", "hyperium"]

[dependencies]
httparse = "0.1"
log = "0.3"
mime = "0.0.11"
num_cpus = "0.2"
rustc-serialize = "0.3"
time = "0.1"
unicase = "0.1"
url = "0.2"
traitobject = "0.0.1"
typeable = "0.1"

[dev-dependencies]
env_logger = "*"

[features]
default = ["ssl"]
# These are grouped together b/c it doesn't really make sense to
# enable one w/o the other
ssl = ["openssl", "cookie"]
nightly = []


[dependencies.cookie]
version = "0.1"
optional = true

[dependencies.openssl]
version = "0.6"
optional = true
