[package]

name = "hyper"
version = "0.10.0-a.0"
description = "A modern HTTP library."
readme = "README.md"
documentation = "http://hyperium.github.io/hyper"
repository = "https://github.com/hyperium/hyper"
license = "MIT"
authors = ["Sean McArthur <sean.monstar@gmail.com>"]
keywords = ["http", "hyper", "hyperium"]

[dependencies]
futures = "0.1.7"
futures-cpupool = "0.1"
httparse = "1.0"
language-tags = "0.2"
log = "0.3"
mime = "0.2"
mio = "0.6"
native-tls = "0.1.0"
rustc-serialize = "0.3"
time = "0.1"
tokio-core = "0.1"
tokio-tls = {git = "https://github.com/tokio-rs/tokio-tls"}
tokio-proto = {git = "https://github.com/tokio-rs/tokio-proto"}
tokio-service = {git = "https://github.com/tokio-rs/tokio-service"}
unicase = "1.0"
url = "1.0"
vecio = "0.1"

[dependencies.cookie]
version = "0.3"
default-features = false

[dev-dependencies]
num_cpus = "1.0"
pretty_env_logger = "0.1"

[features]
default = []
nightly = []
