[package]

name = "hyper"
version = "0.2.1"
description = "A modern HTTP library."
readme = "README.md"
documentation = "http://hyperium.github.io/hyper/hyper/index.html"
repository = "https://github.com/hyperium/hyper"
license = "MIT"
authors = ["Sean McArthur <sean.monstar@gmail.com>",
           "Jonathan Reem <jonathan.reem@gmail.com>"]
keywords = ["http", "hyper", "hyperium"]

[dependencies]
cookie = "*"
log = ">= 0.2.0"
mime = "*"
openssl = "*"
rustc-serialize = "*"
time = "*"
unicase = "*"
unsafe-any = "*"
url = "*"
rand = "*" # src/client/mod.rs // for generate some keys which cookiejar needs.