[package]
authors = ["Sean McArthur <sean.monstar@gmail.com>"]
description = "A modern HTTP library."
documentation = "http://hyperium.github.io/hyper"
keywords = ["http", "hyper", "hyperium"]
license = "MIT"
name = "hyper"
readme = "README.md"
repository = "https://github.com/hyperium/hyper"
version = "0.10.0-a.0"

[dependencies]
futures = "0.1.6"
futures-cpupool = "0.1.2"
httparse = "1.0"
language-tags = "0.2"
log = "0.3"
mime = "0.2"
mio = "0.6"
rustc-serialize = "0.3"
spmc = "0.2"
time = "0.1"
tokio-core = "0.1.1"
unicase = "1.0"
url = "1.0"
vecio = "0.1"

[dependencies.bytes]
git = "https://github.com/carllerche/bytes"

[dependencies.cookie]
default-features = false
version = "0.3"

[dependencies.serde]
optional = true
version = "0.8"

[dependencies.tokio-proto]
git = "https://github.com/tokio-rs/tokio-proto"

[dependencies.tokio-service]
git = "https://github.com/tokio-rs/tokio-service"

[dev-dependencies]
num_cpus = "1.0"

[dev-dependencies.pretty_env_logger]
git = "https://github.com/seanmonstar/pretty-env-logger"

[features]
default = []
nightly = []
serde-serialization = ["serde", "mime/serde"]
