[package]

name = "hyper-net"
version = "0.1.0"
authors = ["Sean McArthur <sean.monstar@gmail.com>"]

[dependencies.hyper-core]
path = "../core"
[dependencies.openssl]
version = "*"
[dependencies.unsafe-any]
version = "*"

